# NOTE: update this with your service name
service: notes-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1
  environment:
    tableName: notes
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  addItem:
    handler: handlers/addItem.main
    events:
      - http:
          path: notes
          method: post
          authorizer: aws_iam
  getItem:
    handler: handlers/getItem.main
    events:
      - http:
          path: notes/{id}
          method: get
          authorizer: aws_iam
  getList:
    handler: handlers/getList.main
    events:
      - http:
          path: notes
          method: get
          authorizer: aws_iam
  updateItem:
    handler: handlers/updateItem.main
    events:
      - http:
          path: notes/{id}
          method: put
          authorizer: aws_iam
  deleteItem:
    handler: handlers/deleteItem.main
    events:
      - http:
          path: notes/{id}
          method: delete
          authorizer: aws_iam
